### ISSUE TITLE
error while installing django-users2

### ISSUE THREAD

**Issue by Alwerdani** [mishbahr/django-users2#15]
Hi, i'm trying to install the package via pip3 on  digitalocean droplet.
I get this error msg:
```
pip3 install django-users2
Downloading/unpacking django-users2
  Downloading django-users2-0.1.14.tar.gz
  Running setup.py (path:/tmp/pip_build_root/django-users2/setup.py) egg_info for package django-users2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/django-users2/setup.py", line 23, in <module>
        readme = open('README.rst').read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1959: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/django-users2/setup.py", line 23, in <module>

    readme = open('README.rst').read()

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1959: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/django-users2
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by mishbahr** [comment]
Somehow I managed to "unwatch" this repo. So didn't get a notification for this issue. I apologize for a very late reply. I'll look into this issue as soon as I can.

- Mishbah

**Comment by mishbahr** [comment]
@Alwerdani I've updated the `setup.py` to use `codecs`. Let me know if this fixes your issue.

**Comment by Alwerdani** [comment]
Thank you  by cloning the last commit it is work correctly
