### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by antoniosap** [mishbahr/django-users2#35]
```
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'users.User'

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fef43ee30d0>
Traceback (most recent call last):
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/antonio/workspace-legrand/myhome-cloud/mhc/mhc/urls.py", line 26, in <module>
    url(r'^', include('app.urls')),
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/antonio/workspace-legrand/myhome-cloud/mhc/app/urls.py", line 5, in <module>
    from . import views
  File "/home/antonio/workspace-legrand/myhome-cloud/mhc/app/views.py", line 58, in <module>
    class UserViewSet(viewsets.ReadOnlyModelViewSet):
  File "/home/antonio/workspace-legrand/myhome-cloud/mhc/app/views.py", line 62, in UserViewSet
    queryset = User.objects.all()
  File "/home/antonio/anaconda3/envs/myhome-cloud/lib/python3.6/site-packages/django/db/models/manager.py", line 190, in __get__
    cls._meta.swapped,
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'users.User'
```

any ideas ?

**Comment by mishbahr** [comment]
When ever you use the `User` model .. make sure you use `get_user_model()`

```
from django.contrib.auth import get_user_model
User = get_user_model()

```
